<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="soaml" nsURI="http://www.eclipse.org/sirius/sample/soaml" nsPrefix="soaml">
  <eClassifiers xsi:type="ecore:EClass" name="Participant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilityrealization"
        upperBound="-1" eType="#//CapabilityRealization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumer" eType="#//Consumer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" eType="#//Provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="#//Participant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collaboration" eType="#//Collaboration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityRealization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capability" eType="#//Capability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Consumer" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Provider" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Capability"/>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityExposure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capability" eType="#//Capability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInerface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilityexposure" upperBound="-1"
        eType="#//CapabilityExposure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceinerface" eType="#//ServiceInerface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicechannel" eType="#//ServiceChannel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceinerface" eType="#//ServiceInerface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicechannel" eType="#//ServiceChannel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceChannel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Collaboration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceArchitecture" eSuperTypes="#//Collaboration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceContract" eSuperTypes="#//Collaboration"/>
</ecore:EPackage>
